module Isorun
  class Context
    class Import
      CACHE_KEY: string

      @context: Context

      attr_reader context: Context
      attr_reader export_names: [string]

      def from: -> [Function|Object]
    end
  end
end
