[package]
name = "isorun"
version = "0.1.0"
edition = "2021"
authors = ["Hannes Moser <box@hannesmoser.at>"]
homepage = "https://github.com/eliias/isorun"
repository = "https://github.com/eliias/isorun"

[dependencies]
deno_console = "0.73.0"
deno_core = "0.155.0"
deno_node = "0.10.0"
deno_fetch = "0.96.0"
deno_runtime = "0.81.0"
deno_url = "0.73.0"
deno_web = "0.104.0"
deno_webidl = "0.73.0"
magnus = { git = "https://github.com/matsadler/magnus", rev = "cc852bfa31992d882d42509b1165eb5f67f9dc2c" } # waiting for release with full rb-sys backend
tokio = { version = "1.21.2", features = ["full"] }
v8 = "0.53.1"

[dev-dependencies]
magnus = { git = "https://github.com/matsadler/magnus", rev = "cc852bfa31992d882d42509b1165eb5f67f9dc2c", features = ["embed"] } # waiting for release with full rb-sys backend

[lib]
name = "isorun"
crate-type = ["cdylib"]
