[package]
name = "isorun"
version = "0.1.0"
edition = "2021"
authors = ["Hannes Moser <box@hannesmoser.at>"]
homepage = "https://github.com/eliias/isorun"
repository = "https://github.com/eliias/isorun"

[dependencies]
deno_console = "0.74.0"
deno_core = "0.156.0"
deno_fetch = "0.97.0"
deno_runtime = "0.82.0"
deno_url = "0.74.0"
deno_web = "0.105.0"
deno_webidl = "0.74.0"
lazy_static = "1.4.0"
magnus = { git = "https://github.com/eliias/magnus", branch = "add-gvl-api" }
tokio = { version = "1.21.2", features = ["full"] }
v8 = "0.54.0"

[dev-dependencies]
magnus = { git = "https://github.com/eliias/magnus", branch = "add-gvl-api", features = ["embed"] } # waiting for release with full rb-sys backend

[lib]
name = "isorun"
crate-type = ["cdylib"]
