[package]
name = "isorun"
version = "0.1.11"
edition = "2021"
authors = ["Hannes Moser <box@hannesmoser.at>"]
homepage = "https://github.com/eliias/isorun"
repository = "https://github.com/eliias/isorun"

[dependencies]
deno_console = "0.86.0"
deno_core = "0.168.0"
deno_fetch = "0.110.0"
deno_runtime = "0.94.0"
deno_url = "0.86.0"
deno_web = "0.120.0"
deno_webidl = "0.86.0"
lazy_static = "1.4.0"
magnus = { git = "https://github.com/eliias/magnus", rev = "75e2ba89d12af8c51d2bbbb137da2eac3fc966e3" }
tokio = { version = "1.21.1", features = ["full"] }
v8 = "0.60.1"

[dev-dependencies]
magnus = { git = "https://github.com/eliias/magnus", rev = "75e2ba89d12af8c51d2bbbb137da2eac3fc966e3", features = ["embed"] }

[lib]
name = "isorun"
crate-type = ["cdylib"]
