[package]
name = "isorun"
version = "0.1.7"
edition = "2021"
authors = ["Hannes Moser <box@hannesmoser.at>"]
homepage = "https://github.com/eliias/isorun"
repository = "https://github.com/eliias/isorun"

[dependencies]
deno_console = "0.82.0"
deno_core = "0.164.0"
deno_fetch = "0.106.0"
deno_runtime = "0.90.0"
deno_url = "0.82.0"
deno_web = "0.113.0"
deno_webidl = "0.82.0"
lazy_static = "1.4.0"
magnus = { git = "https://github.com/eliias/magnus", rev = "3289eeda7ea63831c0277b153666f1efab3866bb" }
tokio = { version = "1.21.1", features = ["full"] }
v8 = "0.60.0"

[dev-dependencies]
magnus = { git = "https://github.com/eliias/magnus", rev = "3289eeda7ea63831c0277b153666f1efab3866bb", features = ["embed"] }

[lib]
name = "isorun"
crate-type = ["cdylib"]
