require:
  - "rubocop-performance"
  - "rubocop-rspec"

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "examples/**/*"
    - "node_modules/**/*"
    - "packages/**/*"
    - "pkg/**/*"
    - "target/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
