module Isorun
  class Module
    CACHE_KEY: untyped
    CallOptions: untyped
    DEFAULT_ENTRYPOINT: untyped
    DEFAULT_RECEIVER: untyped
    DEFAULT_RESOLVER: untyped

    @bundle_path: string
    @entrypoint: string

    @module_mtime: untyped

    attr_reader bundle_path: string
    attr_writer bundle_resolver: Proc
    attr_reader entrypoint: string

    attr_writer entrypoint: untyped
    attr_writer mesage_receiver: untyped

    attr_writer message_receiver: untyped

    def bundle_resolver: -> string

    def call: -> untyped

    def exist?: -> bool

    def import: -> untyped

    def message_receiver: -> string

    def resolve_bundle_path: -> string

    private

    def environment: -> string

    def force_reload: -> bool
  end
end
