module Isorun
  module Resolver
    SIMPLE_RESOLVER: Proc
    SSR_APP_RESOLVER: Proc
    SSR_VITE_APP_RESOLVER: Proc

    def self.module_path: -> string

    private

    def asset_path: -> string
  end
end
