name: Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
        ruby: [ "3.0", "3.1", "3.2" ]
    steps:
      - name: Install protobuf
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y protobuf-compiler

      - name: Install protobuf
        if: matrix.os == 'macos-latest'
        run: brew install protobuf

      - uses: actions/checkout@v3

      - uses: oxidize-rb/actions/setup-ruby-and-rust@main
        with:
          rubygems: latest
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cargo-cache: true
          cache-version: v1

      - name: Run ruby tests
        run: bundle exec rake

      - name: Lint rust
        run: |
          cargo clippy
          cargo fmt --check
